name: "Terraform destroy"

on:
  push:
    branches:
      - destroybranch

jobs:
  terraform:
    env:
      ARM_CLIENT_ID : ${{SECRETS.CLIENT_ID}}
      ARM_CLIENT_SECRET : ${{SECRETS.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID : ${{SECRETS.SUBSCRIPTION}}
      ARM_TENANT_ID : ${{SECRETS.TENANT_ID}}
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/iac
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: Init
        run: terraform init -backend-config="sas_token=${{ SECRETS.SAS_TOKEN }}"

      - name: Terraform Validate
        id: Validate
        run: terraform validate -no-color

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve