name: "Terraform deploy"

on:
  push:
    branches:
      - "main"

jobs:
  terraform:
    env:
      ARM_CLIENT_ID : ${{SECRETS.CLIENT_ID}}
      ARM_CLIENT_SECRET : ${{SECRETS.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID : ${{SECRETS.SUBSCRIPTION}}
      ARM_TENANT_ID : ${{SECRETS.TENANT_ID}}
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/iac
    steps:
      - uses: actions/checkout@2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: Init
        run: terraform Init

      - name: Terraform Validate
        id: Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve